[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps
EditorStartupMap=/Game/Maps
GlobalDefaultGameMode=/Script/AegisTacticalViewer.AegisTacticalViewerGameMode

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="/Script/TP_Blank",NewGameName="/Script/AegisTacticalViewer")

; Production Demo quality settings
[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.AutoExposure=True
r.DefaultFeature.AmbientOcclusion=True
r.AmbientOcclusionLevels=2
r.AmbientOcclusionMaxQuality=50
r.DefaultFeature.Bloom=True
r.BloomQuality=3
r.EyeAdaptationQuality=1
r.Streaming.PoolSize=2000
r.Tonemapper.Sharpen=0.45
r.AntiAliasingMethod=4
r.ScreenPercentage.Default=85
r.TSR.History.ScreenPercentage=100
r.VolumetricFog=1
r.PSOPrecaching=1
r.PSOPrecache.Components=1
r.Nanite.MaxPixelsPerEdge=1

[/Script/Engine.ExponentialHeightFogComponent]
FogDensity=0.008
FogHeightFalloff=0.15
StartDistance=800.0

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=E318F91F43F79F57000FAC9B7A9BD76E
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=
